force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <description>This custom object is used to describe the candidate selected for an interview.</description>
    <label>Candidate</label>
    <nameField>
        <label>Candidate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/Applied_Position__c.field-meta.xml
<CustomField>
    <fullName>Applied_Position__c</fullName>
    <label>Applied Position</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Analyst</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Solution Architect</fullName>
            </value>
            <value>
                <fullName>Solution Principal</fullName>
            </value>
            <value>
                <fullName>Principal Consultant</fullName>
            </value>
            <value>
                <fullName>Consultant Manager</fullName>
            </value>
            <value>
                <fullName>Client Service Lead</fullName>
            </value>
            <value>
                <fullName>Practice Area Lead</fullName>
            </value>
            <value>
                <fullName>Client Service Partner</fullName>
            </value>
            <value>
                <fullName>Practice Area Director</fullName>
            </value>
            <value>
                <fullName>Managing Director</fullName>
            </value>
            <value>
                <fullName>General Manager</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Interview_Time__c.field-meta.xml
<CustomField>
    <fullName>Interview_Time__c</fullName>
    <description>This is the day and the time of interview of the candidate.</description>
    <label>Interview Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Practice__c.field-meta.xml
<CustomField>
    <fullName>Practice__c</fullName>
    <label>Practice</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Build</fullName>
            </value>
            <value>
                <fullName>Business Advisory Services</fullName>
            </value>
            <value>
                <fullName>Customer Engagement</fullName>
            </value>
            <value>
                <fullName>Data and Analytics</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestPOC.cls
public with sharing class TestPOC {

    public static void matchCandidatesWithInterviers(List<Candidate__c> newInsertedCandidateList) {
        Candidate__c candy = newInsertedCandidateList[0];
        //Candidate__c candy = [SELECT Name, Interview_Time__c, Applied_Position__c, Practice__c FROM Candidate__c WHERE Name = 'GoGo' LIMIT 1];
        List<Event> userEvents = [Select Description, StartDateTime, EndDateTime, ActivityDateTime, Location, IsAllDayEvent, OwnerId FROM Event WHERE OwnerId ='0053h000001dTtBAAU' ];

        For(Event eve : userEvents){
            if(eve.StartDateTime == candy.Interview_Time__c){
                System.debug('XXXXXCandidate interview time' + candy.Interview_Time__c);
                System.debug('XXXXXevent time' + eve.StartDateTime);
                System.debug('There is a match with the interviewer');
                sendEmail(eve);
                
            }
            else{
                System.debug('YYYYYevent time' + eve.StartDateTime);
                System.debug('YYYYYCandidate interview time' + candy.Interview_Time__c);
                System.debug('No match');
            }
        }
        
    }

    public static void sendEmail(Event eve) {

        //Creating an email for the lead 
        Messaging.SingleEmailMessage[] mails = new Messaging.SingleEmailMessage[0];
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        mail.setSenderDisplayName('Slalom Recruiting');
        mail.setTargetObjectId(eve.OwnerId);            
        mail.setSubject('This is the subject');
        mail.setSaveAsActivity(false);
        // mail.setPlainTextBody(ld.Owner.Name + ',' + '\n' + 'Please be advised that the ' + ld.Name + ' was created on ' + 
        //                      ld.CreatedDate + ' and has not been converted.' + '\n' + 'Feel free to access this record from the link below and update it accordingly:' + 
        //                      '\n' + 'Link: '+ URL.getSalesforceBaseUrl().toExternalForm()+ '/'+ld.Id + '\n' + 'Best Regards,'
        //                      + '\n' + 'Salesforce Automation');
        mail.setPlainTextBody('This is the email of the text');
        mails.add(mail);
        Messaging.sendEmail(mails);
        
    }
    
}